/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.sabrix;

import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Module;
import org.mule.api.annotations.Processor;
import org.mule.modules.sabrix.internal.CollectionInliner;

import ar.com.zauber.commons.mom.MapObjectMapper;
import ar.com.zauber.commons.mom.MapObjectMappers;
import ar.com.zauber.commons.mom.style.impl.CXFStyle;

import com.sabrix.services.taxservice._2009_12_20.DocumentCollection;
import com.sabrix.services.taxservice._2009_12_20.HostRequestInfo;
import com.sabrix.services.taxservice._2009_12_20.TaxResponse;

import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;

import org.apache.commons.lang.Validate;

/**
 * SabrixModule
 *
 * @author flbulgarelli
 */
@Module(name = "sabrix", schemaVersion = "1.0")
public class SabrixModule
{
    /**
     * The Sabrix login username
     */
    @Configurable
    private String username;

    /**
     * The Sabrix login password
     */
    @Configurable
    private String password;

    /**
     * The Sabrix
     */
    @Configurable
    private String endpoint;

    private SabrixClient sabrixClient;

    private final MapObjectMapper mom;
    {
        mom = MapObjectMappers.defaultWithPackage("com.sabrix.services")
            .withSetterStyle(CXFStyle.STYLE)
            .withInterceptor(new CollectionInliner())
            .build();
    }


    /**
     * Calculate taxes using host information, transaction information, and an
     * external company id
     *
     * {@sample.xml ../../../doc/connector.xml.sample sabrix:get-taxes}
     *
     * @param documents TODO
     * @param externalCompanyId TODO
     * @param hostRequestInfo TODO
     * @return TODO
     */
    @Processor
    public TaxResponse getTaxes(List<Map<String, Object>> documents,
                                String externalCompanyId,
                                Map<String, Object> hostRequestInfo)
    {
        return sabrixClient.getTaxes(
            (DocumentCollection) mom.unmap(documents, DocumentCollection.class),
            externalCompanyId,
            (HostRequestInfo) mom.unmap(hostRequestInfo, HostRequestInfo.class));
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public void setUsername(String username)
    {
        this.username = username;
    }

    public void setEndpoint(String endpoint)
    {
        this.endpoint = endpoint;
    }

    @PostConstruct
    public void init() {
        if(sabrixClient == null) {
            Validate.notNull(password);
            Validate.notNull(username);
            Validate.notNull(endpoint);
            sabrixClient = new CxfSabrixClient(endpoint, username, password);
        }
    }

    public void setSabrixClient(SabrixClient sabrixClient)
    {
        this.sabrixClient = sabrixClient;
    }

}
