/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.sabrix;

import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Module;
import org.mule.api.annotations.Processor;

/**
 * SabrixModule
 *
 * @author flbulgarelli
 */
@Module(name = "sabrix", schemaVersion = "1.0")
public class SabrixModule
{
    /**
     * The Sabrix login username
     */
    @Configurable
    private String username;

    /**
     * The Sabrix login password
     */
    @Configurable
    private String password;

    /**
     * Calculate taxes using host information, transaction information, and an
     * external company id
     *
     * {@sample.xml ../../../doc/connector.xml.sample sabrix:get-taxes}
     */
    @Processor
    public void getTaxes()
    {

    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public void setUsername(String username)
    {
        this.username = username;
    }

}
